import AdminLoginInput from "@/components/Admin/Login/AdminLoginInput";
import AdminNavbar from "@/components/Admin/Side/AdminNavbar";
import AuthImage from "@/components/login/AuthImage";
import LoginInput from "@/components/login/LoginInput";
import Head from "next/head";
import React from "react";

const login = () => {
  return (
    <>
      <Head>
        <title>Kira Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <AdminNavbar />
      <div>
        <div className="flex sm:mt-0 mt-24 flex-col sm:flex-row justify-around items-center  h-[80vh]">
          <div>
            <AdminLoginInput />
          </div>
          <div className="mt-10 sm:mt-0">
            <AuthImage img="https://i.postimg.cc/sXHyLbCs/image.png" />
          </div>
        </div>
      </div>
    </>
  );
};

export default login;
