import SearchBar from "../components/Home/SearchBar";
import Head from "next/head";
import Navbar from "../components/Reusable/navbar";
import FollowingPage from "@/components/Home/FollowingPage";
import PostGrid from "@/components/Home/PostGrid";
import Modal from "@/components/Reusable/Modal";
import { ToastContainer } from "react-toastify";
import { auth } from "@/lib/firebase";

export default function Home() {
  if (!auth.currentUser?.emailVerified)
    return (
      <div>
        <Navbar />
        <h1 className="flex justify-center items-center h-[90vh] capitalize text-3xl">
          please verify your email To continue using Kira
        </h1>
      </div>
    );
  return (
    <>
      <Head>
        <title>Kira Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main>
        <Navbar />
        {/* sqaure with blur, absolute */}

        <section className="flex justify-between items-start px-5 py-5 gap-x-10">
          <div className="w-full">
            <SearchBar />
            <PostGrid />
          </div>
          <div className="sm:flex fixed right-24 hidden flex-col gap-5">
            <FollowingPage />
          </div>
        </section>

        <Modal />
      </main>
      <ToastContainer />
    </>
  );
}
