import AuthImage from "@/components/login/AuthImage";
import SignupInput from "@/components/login/SignupInput";
import Navbar from "@/components/Reusable/navbar";
import { auth } from "@/lib/firebase";
import { onAuthStateChanged } from "firebase/auth";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const login = () => {
  const router = useRouter();

  if (auth.currentUser) router.push("/");
  return (
    <div>
      <Head>
        <title>Kira Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Navbar />

      <div className="flex sm:mt-0 mt-24 flex-col sm:flex-row justify-around items-center  h-[80vh]">
        <div>
          <SignupInput />
        </div>
        <div className="mt-10 sm:mt-0">
          <AuthImage img="https://i.postimg.cc/9MwbZqbV/image.png" />
        </div>
      </div>
    </div>
  );
};

export default login;
